spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop               # Application ?? ? DDL Option
    show-sql: true                        # Query ?? ? console?? ?? ??
    defer-datasource-initialization: true # data.sql? ???? ??? ??

  sql:
    init:
      mode: always                        # data.sql? ???? ??? ??
